version: 2
jobs:
  build:
    docker:
      - image: circleci/node:16.15.0

    steps:
      - checkout

      - run:
          name: Setup NPM Token
          command: |
              echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
              echo "registry=https://registry.npmjs.org/" >> .npmrc
      - run:
          name: Install Dependencies
          command: pnpm install --frozen-lockfile
      - run:
          name: lint
          command: ./run lint
      - run:
          name: check types
          command: ./run types
      - run:
          name: test
          command: ./run test
      - run:
          name: build
          command: ./run build
      - run:
          name: release
          command: pnpm run semantic-release
