version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:16.15.0

    steps:
      - checkout

      - run:
          name: install pnpm
          command: npm install -g pnpm

      - run:
          name: setup NPM token
          command: |
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
            echo "registry=https://registry.npmjs.org/" >> .npmrc
      - run:
          name: install dependencies
          command: pnpm install --frozen-lockfile
      - run:
          name: lint
          command: ./run lint
      - run:
          name: check types
          command: ./run types
      - run:
          name: test
          command: ./run test
      - run:
          name: build
          command: ./run build
      - run:
          name: release
          command: pnpm run semantic-release

workflows:
  version: 2
  build:
    jobs:
      - build:
          context:
            - npm-release
